/*
 * BootManager_cfg.h
 *
 *  Created on: Mar 3, 2025
 *      Author: Issac Amin
 */

#ifndef BOOTLOADER_CFG_H_
#define BOOTLOADER_CFG_H_

#include <stdint.h>

#define BOOTLOADER_RESET_VECTOR_ADDRESS 			0x0f4c0000
#define FLASHBANK_A_BASE_ADDRESS					0x01000000
#define FLASHBANK_B_BASE_ADDRESS					0x01200000
#define FLASHBANK_A_ENTRY_POINT						FLASHBANK_A_BASE_ADDRESS
#define FLASHBANK_B_ENTRY_POINT						FLASHBANK_B_BASE_ADDRESS
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_1		16384U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_2		278528U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_3		540672U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_4		802816U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_5		1064960U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_6		1327104U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_7		1589248U
#define FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_8		1851392U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_1		2113536U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_2		2375680U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_3		2637824U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_4		2899968U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_5		3162112U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_6		3424256U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_7		3686400U
#define FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_8		3948544U
#define BOOTLOADER_LOGICAL_ADDRESS_SECTOR_1			4210688U
#define BOOTLOADER_LOGICAL_ADDRESS_SECTOR_2			4472832U
#define BOOTLOADER_LOGICAL_ADDRESS_SECTOR_3			4734976U
#define FLASHBANK_A_CRC								(FLASHBANK_A_LOGICAL_ADDRESS_SECTOR_1 + FLASHBANK_SIZE - PAGE_SIZE)
#define FLASHBANK_B_CRC								(FLASHBANK_B_LOGICAL_ADDRESS_SECTOR_1 + FLASHBANK_SIZE - PAGE_SIZE)
#define FLASHBANK_SIZE								2097152U
#define SECTOR_SIZE									16384U //262144U
#define PAGE_SIZE									8U
#define QUAD_PAGE_SIZE								128U
#define CRC_CCITT_START_VALUE 						0U


typedef struct{
	uint32_t app_length;
	uint16_t crc_ccitt;
	uint16_t reserved_section[61];
}meta_data;

typedef void (*func_ptr_t)(void);

extern void (*ptr_to_bootloader)(void);
extern void (*ptr_to_flashbank_A)(void);
extern void (*ptr_to_flashbank_B)(void);

#endif /* BOOTLOADER_CFG_H_ */
