/*
 * Copyright (c) 2018-2019 Faculty of Engineering Ain Shams University Dr.Sherif Hammad Email: Sherif.hammad@eng.asu.edu.eg Eng.Mohamed abdelhay Email: mhmd.a.elhay@gmail.com.
 *
 * This file is part of ASUSAR
 * (see https://github.com/asusar/communication-stack).
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Configuration of module: CanIf (CanIf_Cfg.c)
 *
 * Created by:
 * Copyright:
 *
 * Configured for (MCU):    TMS570
 *
 * Module vendor:           ArcCore
 * Generator version:       2.0.6
 *
 * Generated by Arctic Studio (http://arccore.com)
 */
#include "CanIf.h"
#include "CanTp.h"

extern void CanTp_TxConfirmation(PduIdType, Std_ReturnType);

// /* #if defined(USE_PDUR) */
// #include "PduR.h"
// #include "PduR_CanIf.h"
// #include "PduR_PbCfg.h"
// /*#endif */
// #if defined(USE_CANNM)
// #include "CanNm_Cbk.h"
// #endif
// #include <stdlib.h>
// #include "Can_Driver/Can_Cfg.h"


const CanIf_TxPduConfigType CanIfTxPduConfigData[] = { 
		{
				.CanIfTxPduBufferRef = NULL,
				.CanIfUserTxConfirmation = 0,
				.CanIfCanTxPduIdCanId = (uint32)1,
				.CanIfTxPduId = (uint32) 0,
				.CanIfTxPduIdCanIdType = CANIF_CAN_ID_TYPE_11,
				.CanIfCanTxPduType = CANIF_PDU_TYPE_STATIC,
				.CanIfCanTxPduIdDlc = (uint8) 8,
				.CanIfUserTxConfirmation = CanTp_TxConfirmation
#if ( CANIF_READTXPDU_NOTIFY_STATUS_API == STD_ON )
				.CanIfReadTxPduNotifyStatus = false,
#endif
		}, 
		{
			.CanIfTxPduBufferRef = NULL,
			.CanIfUserTxConfirmation = 0,
			.CanIfCanTxPduIdCanId = (uint32)1,
			.CanIfTxPduId = (uint32) 1,
			.CanIfTxPduIdCanIdType = CANIF_CAN_ID_TYPE_11,
			.CanIfCanTxPduType = CANIF_PDU_TYPE_STATIC,
			.CanIfCanTxPduIdDlc = (uint8) 8,
			.CanIfUserTxConfirmation = CanTp_TxConfirmation
#if ( CANIF_READTXPDU_NOTIFY_STATUS_API == STD_ON )
			.CanIfReadTxPduNotifyStatus = false,
#endif
	}
};

const CanIf_RxPduConfigType CanIfRxPduConfigData[] = {
		{
				.CanIfCanRxPduCanId =(uint32) 0,
				.CanIfUserRxIndication = 0,
				.CanIfCanRxPduId = (uint32) 0,
				.CanIfCanRxPduDlc = (uint8) 8,
				.CanIfUserRxIndication = CanTp_RxIndication
#if ( CANIF_CANPDUID_READDATA_API == STD_ON )
				.CanIfReadRxPduData = false,
#endif
#if ( CANIF_READTXPDU_NOTIFY_STATUS_API == STD_ON )
				.CanIfReadRxPduNotifyStatus = false,
#endif
		}, 
		{
		.CanIfCanRxPduCanId =(uint32) 1,
		.CanIfUserRxIndication = 0,
		.CanIfCanRxPduId = (uint32) 1,
		.CanIfCanRxPduDlc = (uint8) 8,
		.CanIfUserRxIndication = CanTp_RxIndication
#if ( CANIF_CANPDUID_READDATA_API == STD_ON )
		.CanIfReadRxPduData = false,
#endif
#if ( CANIF_READTXPDU_NOTIFY_STATUS_API == STD_ON )
		.CanIfReadRxPduNotifyStatus = false,
#endif
		}
};

/* This container contains the init parameters of the CAN */
/* Multiplicity 1..* */
const CanIf_InitConfigType CanIfInitConfig =
{
		.CanIfConfigSet = (uint32) 0, /* Not used   */
		.CanIfNumberOfCanRxPduIds = (uint32)2,
		.CanIfNumberOfCanTXPduIds = (uint32)2,
		.CanIfNumberOfDynamicCanTXPduIds =(uint32) 0, /* Not used */

		/* Containers */
		.CanIfRxPduConfigPtr = CanIfRxPduConfigData,
		.CanIfTxPduConfigPtr = CanIfTxPduConfigData,
};

/* This container includes all necessary configuration sub-containers */
/* according the CAN Interface configuration structure. */
CanIf_ConfigType CanIf_Config =
{
		.InitConfig = &CanIfInitConfig,
};


const CanIf_HthConfigType CanIf_hthConfigTypeInstance[] = {
		{CANIF_HANDLE_TYPE_BASIC, CanHardwareObject_1}
};


CanIf_TxBufferCfg_t TxBufferCfg1[]={
		{
				.BufferInfoPtr = NULL,
				.HthIndex = 0,
				.BufferSize = 0
		}
};


/* This container contains the init parameters of the CAN */
/* Multiplicity 1..* */
const CanIf_InitConfigType CanIfInitConfig_Test =
{
		.CanIfConfigSet = (uint32) 0, /* Not used   */
		.CanIfNumberOfCanRxPduIds = (uint32)2,
		.CanIfNumberOfCanTXPduIds = (uint32)2,
		.CanIfNumberOfDynamicCanTXPduIds =(uint32) 0, /* Not used */

		/* Containers */
		.CanIfRxPduConfigPtr = CanIfRxPduConfigData,
		.CanIfTxPduConfigPtr = CanIfTxPduConfigData,
};

/* This container includes all necessary configuration sub-containers */
/* according the CAN Interface configuration structure. */
CanIf_ConfigType CanIf_Config_Test =
{
		.InitConfig = &CanIfInitConfig_Test,
};
